{% set name = "hypsoreader" %}
{% set version = "0.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DevAlvaroF/HYPSO-Reading/archive/v{{ version }}.tar.gz
  sha256: b671969fa801ce4a7c196e92a3a202eff691c5a90d237d501bdcb8443276168c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0
    - setuptools_scm  >=3.4
  run:
    - python >=3.9
    - numpy >=1.24
    - gdal =3.6.2
    - cartopy =0.21.1
    - pandas
    - matplotlib
    - geopandas =0.12.2
    - rasterio =1.3.4
    - pyproj =3.4.1

test:
  imports:
    - hypsoreader
  commands:
    - pip check
    - pip list
  requires:
    - pip

about:
  license: GPL-2.0-or-later
  license_file: LICENSE
  home: https://github.com/DevAlvaroF/HYPSO-Reading
  summary: 'Visualization tool for the HYPSO satellite'
  description: |
    hypsoreader is a simple, fast visualization tool for the hyperspectral
    images taken by the HYPSO mission from the Norwegian University of Science and
    Technology (NTNU) for Python 3.9


extra:
  recipe-maintainers:
    - DevAlvaroF
    
