{% set name = "hypsoreader" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DevAlvaroF/HYPSO-Reading/archive/v{{ version }}.tar.gz
  sha256: 171721746c1d8ed2c6a5ec98aa808c1a8e9afb95e1bfc26b37cc3b1bb84d7365

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - pip
    - setuptools >=61.0
    - setuptools_scm  >=3.4
  run:
    - python >=3.9
    - numpy >=1.24
    - gdal =3.6.2
    - cartopy =0.21.1
    - pandas
    - matplotlib
    - geopandas =0.12.2
    - rasterio =1.3.4
    - pyproj =3.4.1
    - netcdf4 >=1.6.3
    - scikit-image >=0.21.0
    - py6s >=1.9.2
    - scipy >=1.11.2
    - pillow
    - shapely >=2.0.1

test:
  imports:
    - hypsoreader
    - gdal
    - rasterio
    - geopandas
  commands:
    - pip check
    - pip list
  requires:
    - pip

about:
  license: GPL-2.0-or-later
  license_file: LICENSE
  home: https://github.com/DevAlvaroF/HYPSO-Reading
  summary: 'Visualization tool for the HYPSO satellite'
  description: |
    hypsoreader is a simple, fast visualization tool for the hyperspectral
    images taken by the HYPSO mission from the Norwegian University of Science and
    Technology (NTNU) for Python 3.9


extra:
  recipe-maintainers:
    - DevAlvaroF
    
